### PR TITLE
Fix extra architectures and gccgo / Go 1.4 compatibility

### PR DESCRIPTION
**Pull request by XRevan86**

### CODE REVIEW

**Comment by XRevan86** [comment]
@harshavardhana, I made this patch primarily to build Syncthing on openSUSE Leap 42.1 :-). It has Go 1.4 in main repositories.
> In-fact for better results one should move to 1.6+ **and use https://golang.org/pkg/crypto/sha256/**

Uhm, does that mean this project is deprecated and only is useful on Go 1.5 or something?

**Comment by harshavardhana** [comment]
Yes stick to recent releases or atleast 1.6 - go1.4 is kind really old in Go world.

**Comment by XRevan86** [comment]
So you are saying sha256-simd is useless, right?

**Comment by harshavardhana** [comment]
What I meant is go 1.4 support is not needed.

**Comment by derlaft** [comment]
>What I meant is go 1.4 support is not needed.

It is needed. As mentioned above, there are distros where new software required, but go can not be upgraded. The distro will survive without this patch merged: it will just ship this patch with the spec. But why not to make the life easier for the others? 

Also, why don't you just accept it? The patch not only breaks nothing, but also removes duplicated code and makes tag stuff more explicit.

>go1.4 is kind really old in Go world.

You are not only developing for Go world, since software depends on your lib. Ofc, it is your right to deny it and make things complicated for everyone.

**Comment by calmh** [comment]
(Disclaimer: not responsible for this package, just following issues here as it's one of our important dependencies and I happen to have an opinion.)

This package is a performance improvement only. If you're looking for performance, the worst thing you can do is compile anything using Go 1.4. Go 1.4 is also unsupported and has security vulnerabilities. Changes to this package must be tested and validated, which is work. Taking on extra work to support Go 1.4 makes little sense to me either.

**Comment by XRevan86** [comment]
@calmh, but in Go it's not easy to choose difference dependencies for different build environments.
At this point the only thing one who wants to keep Go 1.4 support can do is avoid *github.com/minio/sha256-simd* for all Go versions.

**Comment by XRevan86** [comment]
@calmh, but in Go it's not easy to choose difference dependencies for different build environments.
At this point the only thing one who wants to keep Go 1.4 support can do is avoid *github.com/minio/sha256-simd* for all Go versions.
And considering the nature of the Go 1.4 fix, it's not like a true Go 1.4 lover would gain anything from this project.
> Go 1.4 is also unsupported and has security vulnerabilities.

It is maintained in supporting distributions.

**Pull request closed without merging**
